FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app
COPY pom.xml .
COPY .mvn .
COPY mvnw .
COPY src ./src
RUN chmod +x ./mvnw
EXPOSE 8080
EXPOSE 5005
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
