# Stage 1: Build the Vue application
FROM node:lts-alpine AS builder
WORKDIR /app

COPY ./itb-front/package*.json ./
RUN npm install

COPY ./itb-front ./
RUN npm run build

# Stage 2: Serve the built application using Nginx with custom config
FROM nginx:alpine

# สร้าง dir สำหรับ app และ ssl
RUN mkdir -p /app /etc/nginx/ssl

# copy build ของ Vue ไปที่ nginx root
COPY --from=builder /app/dist /usr/share/nginx/html

# copy nginx.conf ของเราไปแทน default
COPY ./itb-front/nginx.conf /etc/nginx/conf.d/default.conf

# expose ทั้ง 80 และ 443
EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
